### ISSUE TITLE
Random Strong Password generator

### ISSUE THREAD

**Issue by SoulPlayer23** [prashantpandey9/create-your-own-what-you-want#37]
A random password generator using python, which is strong for security. I am willing to add this script. Can you assign me?

**Comment by prashantpandey9** [comment]
hi, @SoulPlayer23  if there is no code for that script you can add your own. If there is already an existing script for it then you have to choose a different algorithm, program, or script.

**Comment by shiva-016** [comment]
Hey, @prashantpandey9 I've created my first pull request, and please do check and let me know about the corrections that I must make.

**Comment by prashantpandey9** [comment]
Resolved
