### ISSUE TITLE
Need to add a Readme for WEB directory.

### ISSUE THREAD

**Issue by prashantpandey9** [prashantpandey9/create-your-own-what-you-want#69]
- WEB directory needs a README.md file to track the web projects related to it and also needs to manage their link of deployment.

**Comment by prashantpandey9** [comment]
So, we just need to make a list of all the existing web pages and we have to write a little bit about that webpage.
Also if that webpage has a deployment URL then we have to write that too.
You can test deployment by changing https://prashantpandey9.in/create-your-own-what-you-want/WEB/<your-page-folder-name>/, folder name in this URL. We can also write the username of the contributor in it.

**Comment by AFZL210** [comment]
ok ill add it
